server:
  port: 8085

spring:
  datasource:
    username: root
    password: buaase2020.
    url: jdbc:mysql://123.56.145.79:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    protocol: smtps
    host: smtp.126.com
    username: lrmpublic@126.com
    password: DMVSWWYTENQXEPOL
    spring.mail.smtp.ssl.enable: true
    port: 465
  redis:
    host: 123.56.145.79
    port: 6379

mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:mapper/*.xml

myclient:
  host: 123.56.145.79
  port: 8088
  activate: toActivate